<?xml version="1.0" encoding="utf-8"?><Database Name="PrintItems" Class="Print_dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DEADPOOL\SQLEXPRESS;Initial Catalog=PrintItems;Integrated Security=True" SettingsObjectName="PrintReceipt.Properties.Settings" SettingsPropertyName="PrintItemsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.print_information" Member="print_informations">
    <Type Name="print_information">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customer_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="total_amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="paid_amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="due_amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="information" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>